# Generated by Django 5.2 on 2025-04-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MachineData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.IntegerField()),
                ('date', models.CharField(max_length=40)),
                ('shift', models.CharField(max_length=2)),
                ('ds_ok_count', models.IntegerField()),
                ('ds_ng_count', models.IntegerField()),
                ('ns_ok_count', models.IntegerField()),
                ('ns_ng_count', models.IntegerField()),
                ('ds_ok_perhr', models.CharField(max_length=200)),
                ('ds_ng_perhr', models.CharField(max_length=200)),
                ('ns_ok_perhr', models.CharField(max_length=200)),
                ('ns_ng_perhr', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
