# Generated by Django 5.2 on 2025-05-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinedata',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='machinedata',
            name='ds_ng_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='machinedata',
            name='ds_ng_perhr',
            field=models.CharField(default='[]', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='machinedata',
            name='ds_ok_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='machinedata',
            name='ds_ok_perhr',
            field=models.CharField(default='[]', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='machinedata',
            name='ns_ng_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='machinedata',
            name='ns_ng_perhr',
            field=models.CharField(default='[]', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='machinedata',
            name='ns_ok_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='machinedata',
            name='ns_ok_perhr',
            field=models.CharField(default='[]', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='machinedata',
            name='shift',
            field=models.CharField(default='', max_length=2, null=True),
        ),
    ]
