# Generated by Django 5.2 on 2025-04-30 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinedata',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
