# Generated by Django 5.2 on 2025-05-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_machinedata_updated_alter_machinedata_ds_ng_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinedata',
            name='shift',
            field=models.CharField(default='DS', max_length=2, null=True),
        ),
    ]
