name: Keep Render App Awake

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  keep-awake:
    runs-on: ubuntu-latest
    steps:
      - name: Curl the Render app URL
        run: curl -s https://outputreport.onrender.com/admin/app/machinedata/
